spring:
  datasource:
    url: jdbc:mysql:// host :3306/ database
    username:
    password:

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect